version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data   # 👈 mount Excel data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env

volumes:
  postgres_data:
